'use client';
import {useEffect,useState} from 'react';
import {Search,Plus,Sparkles,Download,Play,BookOpen,Lightbulb,FolderOpen,Upload,ExternalLink,Check,FlaskConical,Calculator,BrainCircuit} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
type Material={id:string;title:string;description:string;subject:string;level:string;kind:string;url?:string;file_key?:string;file_name?:string;uses_ai:number;demo?:boolean;download?:string};

const subjects=['Todas','Matemáticas','Lenguaje','Ciencias','Tecnología e IA','Otras áreas'];
function Choice({value,onChange,items,label}:{value:string;onChange:(s:string)=>void;items:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{items.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select>}
export default function Portal({view}:{view:string}){
 const [items,setItems]=useState<Material[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[subject,setSubject]=useState('Todas'),[level,setLevel]=useState('Todos los niveles'),[canEdit,setCanEdit]=useState(true);
 const [kind,setKind]=useState('actividad'),[area,setArea]=useState('Tecnología e IA'),[grade,setGrade]=useState('Primaria'),[ai,setAI]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[success,setSuccess]=useState(false);
 async function load(){setLoading(true);setError('');try{const r=await fetch('materiales.json',{cache:'no-store'});if(!r.ok)throw new Error('No se pudo cargar el catálogo.');const d=await r.json();if(!Array.isArray(d))throw new Error('El catálogo no tiene el formato esperado.');setItems(d);setCanEdit(true);}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar el catálogo.');}finally{setLoading(false);}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:'filtrar_actividades',description:'Filtra la biblioteca visible por texto.',inputSchema:{type:'object',properties:{texto:{type:'string',maxLength:120}},required:['texto'],additionalProperties:false},annotations:{readOnlyHint:true},execute(input:any){if(typeof input?.texto!=='string'||input.texto.length>120)throw new Error('Texto inválido');setQ(input.texto);return {filtro:input.texto};}},{signal:life.signal})).catch(()=>{});}catch{}return ()=>life.abort()},[]);
 const isProject=view==='proyectos';const pool=items;const filtered=pool.filter(x=>x.kind===(isProject?'proyecto':'actividad')&&(subject==='Todas'||x.subject===subject)&&(level==='Todos los niveles'||x.level===level||x.level==='Todos los niveles')&&(x.title+' '+x.description+' '+x.subject).toLowerCase().includes(q.toLowerCase()));
 async function publish(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(loading||error)return;const form=e.currentTarget,data=new FormData(form);setSuccess(false);setMessage('');try{const resource=String(data.get('url')||'').trim();const download=String(data.get('download')||'').trim();if(!resource&&!download)throw new Error('Agrega un enlace de actividad o una ruta de descarga.');for(const value of [resource,download]){if(value&&!safeLink(value))throw new Error('Usa un enlace https:// o una ruta dentro de materiales/, sin espacios ni puntos dobles.');}const entry:Material={id:crypto.randomUUID(),title:String(data.get('title')).trim(),description:String(data.get('description')).trim(),kind,subject:area,level:grade,uses_ai:ai?1:0,...(resource?{url:resource}:{}),...(download?{download}:{})};const updated=[entry,...items];const blob=new Blob([JSON.stringify(updated,null,2)+'\n'],{type:'application/json;charset=utf-8'});const objectURL=URL.createObjectURL(blob);const a=document.createElement('a');a.href=objectURL;a.download='materiales.json';a.click();setTimeout(()=>URL.revokeObjectURL(objectURL),10000);setItems(updated);setSuccess(true);setMessage('Catálogo preparado y descargado. Para publicarlo, sube materiales.json a la raíz del repositorio y tus archivos a materiales/. La página pública cambiará después de guardar en GitHub.');form.reset();}catch(e){setMessage(e instanceof Error?e.message:'Revisa los datos.');}}
 function safeLink(value:string){if(/^https:\/\//i.test(value)){try{const u=new URL(value);return !u.username&&!u.password;}catch{return false}}return /^materiales\/[a-zA-Z0-9_./-]+$/.test(value)&&!value.includes('..');}
 return <><header className="topbar"><a className="brand" href="index.html"><span className="brand-icon"><Sparkles size={23}/></span><span>Lady<span className="brand-light">Interactiva</span><small>EL AULA DE LAS IDEAS</small></span></a><nav aria-label="Navegación principal">{[['index.html','Inicio','inicio'],['actividades.html','Actividades','actividades'],['proyectos.html','Proyectos','proyectos']].map(([url,name,id])=><a key={id} href={url} aria-current={view===id?'page':undefined}>{name}</a>)}</nav><a className={'publish-link '+(view==='publicar'?'active':'')} href="publicar.html"><Plus size={18}/> Agregar material</a></header>
 <main><div className="eyebrow"><span className="tiny-mark">✳</span> UN ESPACIO DE LA PROFE LADY <span className="eyebrow-line"/></div>
 {view==='publicar'?<><div className="page-heading"><div><span className="section-kicker">DEL AULA A LA COMUNIDAD</span><h1>Comparte una nueva idea<span>.</span></h1><p>Prepara la ficha del material y descarga el catálogo para subirlo a GitHub.</p></div><Upload className="heading-icon" size={60}/></div><div className="publish-layout"><form onSubmit={publish} className="publish-form"><div className="form-title"><span className="number">01</span><h2>Cuéntanos sobre el material</h2></div><div className="form-grid"><label>Tipo de publicación<Choice label="Tipo de publicación" value={kind} onChange={setKind} items={['actividad','proyecto']}/></label><label>Área<Choice label="Área" value={area} onChange={setArea} items={subjects.slice(1)}/></label></div><label>Título<input name="title" required maxLength={120} placeholder="Ej. Una aventura por el sistema solar"/></label><label>Descripción y orientaciones<textarea name="description" required maxLength={3000} rows={5} placeholder="¿Qué aprenderán? Explica cómo usar el material."/></label><label>Nivel educativo<Choice label="Nivel educativo" value={grade} onChange={setGrade} items={['Primaria','Secundaria','Media','Docentes','Todos los niveles']}/></label><label className="check-label"><Checkbox checked={ai} onCheckedChange={v=>setAI(v===true)}/> Incluye actividades con inteligencia artificial</label><div className="form-title"><span className="number">02</span><h2>Agrega tu recurso</h2></div><label>Enlace o ruta de la actividad<input name="url" type="text" placeholder="https://... o materiales/mi-actividad.html"/></label><p className="hint">Para Genially, Canva, sitios web u otras actividades ya publicadas.</p><label>Enlace o ruta para descargar (opcional)<input name="download" type="text" placeholder="materiales/mi-actividad.html o materiales/proyecto.zip"/></label><p className="hint">Sube tus archivos a la carpeta materiales del repositorio. Para una actividad HTML puedes usar la misma ruta en ambos campos; para un ZIP o PDF, basta con la descarga.</p><div className="notice">Este asistente prepara un archivo; no publica automáticamente. Solo quien tenga permiso para editar el repositorio podrá guardar los cambios en GitHub.</div>{message&&<div role="status" className={success?'notice success':'notice error'}>{message}</div>}<button className="button primary" disabled={loading||!!error}><><Download size={18}/>Descargar catálogo actualizado</></button></form><aside className="publishing-aside"><span className="aside-symbol"><Lightbulb size={34}/></span><h2>Una buena idea merece compartirse.</h2><p>Un título claro y unas instrucciones breves ayudan a que cada visitante encuentre lo que necesita.</p><hr/><h3>Todo en su lugar</h3><p><BookOpen size={19}/> Actividades para explorar, practicar y aprender.</p><p><FolderOpen size={19}/> Proyectos para conectar ideas y construir juntos.</p><p><Download size={19}/> Sube archivos a GitHub y ofrece sus enlaces para descarga.</p></aside></div></>:<>
 <section className="intro"><div><span className="section-kicker">{isProject?'APRENDER HACIENDO':'APRENDER TAMBIÉN ES EXPLORAR'}</span><h1>{isProject?<>Ideas que se convierten<br/>en <em>proyectos.</em></>:<>Un clic. Una idea.<br/><em>Un nuevo aprendizaje.</em></>}</h1><p>{isProject?'Experiencias para crear, investigar y aprender en equipo.':'Actividades interactivas, creatividad e inteligencia artificial. Encuentra tu próxima experiencia para el aula.'}</p><div className="intro-tags"><span><BookOpen size={16}/> Explora</span><span><Play size={16}/> Interactúa</span><span><Download size={16}/> Llévalo a tu aula</span></div></div><aside className="feature-note"><span className="note-label"><Sparkles size={17}/> LABORATORIO DE IDEAS</span><h2>La curiosidad<br/>es el comienzo.</h2><p>Recursos para aprender haciendo,<br/>a tu ritmo y con nuevas preguntas.</p><div className="note-footer"><span>Didáctica + creatividad + IA</span><BrainCircuit size={28}/></div></aside></section>
 <section className="library" aria-labelledby="library-title"><div className="library-heading"><div><span className="section-kicker">ELIGE TU PRÓXIMO DESCUBRIMIENTO</span><h2 id="library-title">{isProject?'Proyectos para inspirarte':'Explora la biblioteca'}<span className="count">{filtered.length}</span></h2></div><label className="search"><Search size={19}/><input aria-label="Buscar materiales" value={q} onChange={e=>setQ(e.target.value)} placeholder="¿Qué quieres aprender hoy?"/></label></div><div className="filters"><div className="pills">{subjects.map(s=><button key={s} aria-pressed={subject===s} onClick={()=>setSubject(s)} className={subject===s?'selected':''}>{s}</button>)}</div><Choice label="Filtrar por nivel" value={level} onChange={setLevel} items={['Todos los niveles','Primaria','Secundaria','Media','Docentes']}/></div>{loading&&<p role="status" className="hint">Cargando tus publicaciones…</p>}{error&&<div className="notice error">{error} <button type="button" onClick={load}>Reintentar</button><p>Comprueba que materiales.json esté en la misma carpeta que esta página.</p></div>}<div className="cards">{filtered.map((x,i)=>{const Icon=x.subject==='Matemáticas'?Calculator:x.subject==='Ciencias'?FlaskConical:x.uses_ai?BrainCircuit:BookOpen;const open=x.url;return <article key={x.id} className="activity-card"><div className={'card-cover cover-'+(x.subject==='Matemáticas'?'math':x.subject==='Ciencias'?'science':x.subject==='Lenguaje'?'language':'tech')}><span className="cover-category">{x.subject}</span><Icon size={65} strokeWidth={1.4}/><span className="cover-bottom">{x.kind==='proyecto'?'PROYECTO DE AULA':'APRENDE JUGANDO'}<span>{String(i+1).padStart(2,'0')}</span></span></div><div className="card-body"><div className="card-meta"><span>{x.level}</span>{!!x.uses_ai&&<span><Sparkles size={13}/> Con IA</span>}{x.demo&&<span className="demo-badge">Ejemplo</span>}</div><h3>{x.title}</h3><p>{x.description}</p><div className="card-actions">{open&&<a className="play-link" href={open} target="_blank" rel="noopener noreferrer">{x.kind==='proyecto'?<FolderOpen size={16}/>:<Play size={16}/>} {x.kind==='proyecto'?'Ver proyecto':'Explorar actividad'}</a>}{(x.download||x.demo)&&<a className="download-link" title="Descargar material" aria-label={'Descargar '+x.title} href={x.download||x.url} download><Download size={19}/></a>}{!x.download&&!x.demo&&<ExternalLink size={16}/>}</div></div></article>})}</div>{!filtered.length&&<div className="empty"><Search size={32}/><h3>No encontramos materiales con estos filtros.</h3><button onClick={()=>{setQ('');setSubject('Todas');setLevel('Todos los niveles')}}>Mostrar todos</button></div>}<p className="example-caption">Los materiales marcados como «Ejemplo» son demostraciones. Tus publicaciones aparecerán primero.</p></section>
 <section className="bottom-note"><div><span className="note-label">CREADO PARA COMPARTIR</span><h2>Las buenas ideas crecen en el aula.</h2><p>Un repositorio vivo de experiencias de la profe Lady.</p></div><a href="publicar.html" className="button"><Plus size={18}/> Agregar un material</a></section></>}
 </main><footer><a href="index.html" className="footer-brand"><Sparkles size={19}/>Lady Interactiva</a><p>Didáctica, creatividad e inteligencia artificial.</p><span>Hecho para aprender juntos.</span></footer></>;
}

